project_name: repomix-maker
repomix_options:
  ignore:
    customPatterns:
    - node_modules
    - .git
    - .venv
  output:
    filePath: projects/repomix-maker/outputs/repomix-output.md
    style: markdown
source: git@github.com:petergdoyle/repomix-maker.git
ssh_key: /Users/peter_doyle/.ssh/id_ed25519
